package com.ffe.estimate.model;
// default package
// Generated Oct 11, 2012 5:26:27 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

import com.ffe.common.framework.model.AbstractDomain;

/**
 * EstimateCosting generated by hbm2java
 */
public class EstimateCosting extends AbstractDomain implements java.io.Serializable {

	private Long estimateCostingId;
	private Long estimateCostTypeId;
	private Long serviceId;
	private BigDecimal localCurrentCost;
	private Long currecySelectedId;
	private Integer quantity;
	private BigDecimal totalcost;
	private Estimate estimate;
	private String desc;
	
	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Estimate getEstimate() {
		return estimate;
	}

	public void setEstimate(Estimate estimate) {
		this.estimate = estimate;
	}

	public EstimateCosting() {
	}



	public EstimateCosting(Long estimateCostingId, Long estimateCostTypeId,
			int estimateid, Long serviceId, BigDecimal localCurrentCost,
			Long currecySelectedId, Integer quantity, BigDecimal totalcost) {
		this.estimateCostingId = estimateCostingId;
		this.estimateCostTypeId = estimateCostTypeId;
		this.serviceId = serviceId;
		this.localCurrentCost = localCurrentCost;
		this.currecySelectedId = currecySelectedId;
		this.quantity = quantity;
		this.totalcost = totalcost;
	}

	public Long getEstimateCostingId() {
		return this.estimateCostingId;
	}

	public void setEstimateCostingId(Long estimateCostingId) {
		this.estimateCostingId = estimateCostingId;
	}

	public Long getEstimateCostTypeId() {
		return this.estimateCostTypeId;
	}

	public void setEstimateCostTypeId(Long estimateCostTypeId) {
		this.estimateCostTypeId = estimateCostTypeId;
	}

	public Long getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Long serviceId) {
		this.serviceId = serviceId;
	}

	public BigDecimal getLocalCurrentCost() {
		return this.localCurrentCost;
	}

	public void setLocalCurrentCost(BigDecimal localCurrentCost) {
		this.localCurrentCost = localCurrentCost;
	}

	public Long getCurrecySelectedId() {
		return this.currecySelectedId;
	}

	public void setCurrecySelectedId(Long currecySelectedId) {
		this.currecySelectedId = currecySelectedId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getTotalcost() {
		return this.totalcost;
	}

	public void setTotalcost(BigDecimal totalcost) {
		this.totalcost = totalcost;
	}

}
