package com.ffe.estimate.model;
// default package
// Generated Oct 11, 2012 5:26:27 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * EstimateCostType generated by hbm2java
 */
public class EstimateCostType implements java.io.Serializable {

	private Long estimateCostId;
	private String name;
	private String code;
	private String description;
	private String createdby;
	private String lastupdatedby;
	private Date lastupdateddatetime;
	private Date createddatetime;
	private String deletedflag;

	public EstimateCostType() {
	}

	

	public EstimateCostType(Long estimateCostId, String name, String code,
			String description, String createdby, String lastupdatedby,
			Date lastupdateddatetime, Date createddatetime, String deletedflag) {
		this.estimateCostId = estimateCostId;
		this.name = name;
		this.code = code;
		this.description = description;
		this.createdby = createdby;
		this.lastupdatedby = lastupdatedby;
		this.lastupdateddatetime = lastupdateddatetime;
		this.createddatetime = createddatetime;
		this.deletedflag = deletedflag;
	}

	

	public Long getEstimateCostId() {
		return estimateCostId;
	}



	public void setEstimateCostId(Long estimateCostId) {
		this.estimateCostId = estimateCostId;
	}



	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public String getLastupdatedby() {
		return this.lastupdatedby;
	}

	public void setLastupdatedby(String lastupdatedby) {
		this.lastupdatedby = lastupdatedby;
	}

	public Date getLastupdateddatetime() {
		return this.lastupdateddatetime;
	}

	public void setLastupdateddatetime(Date lastupdateddatetime) {
		this.lastupdateddatetime = lastupdateddatetime;
	}

	public Date getCreateddatetime() {
		return this.createddatetime;
	}

	public void setCreateddatetime(Date createddatetime) {
		this.createddatetime = createddatetime;
	}

	public String getDeletedflag() {
		return this.deletedflag;
	}

	public void setDeletedflag(String deletedflag) {
		this.deletedflag = deletedflag;
	}

}
