package com.ffe.estimate.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.ffe.common.framework.model.AbstractDomain;

/**
 * Estimate generated by hbm2java
 */
public class Estimate extends AbstractDomain implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4744105404866811257L;
	private Long estimateId;
	private Long releaseId;
	private BigDecimal totalUscost;
	private BigDecimal totalLocalCost;
	private List<EstimateCosting> lstEstimateCosting;
	private Long estCostStaId;
	private EstimateCostHeader estimateCostHeader;
	public EstimateCostHeader getEstimateCostHeader() {
		return estimateCostHeader;
	}

	public void setEstimateCostHeader(EstimateCostHeader estimateCostHeader) {
		this.estimateCostHeader = estimateCostHeader;
	}

	private String desc;

	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

	public Long getEstCostStaId() {
		return estCostStaId;
	}

	public void setEstCostStaId(Long estCostStaId) {
		this.estCostStaId = estCostStaId;
	}

	public List<EstimateCosting> getLstEstimateCosting() {
		return lstEstimateCosting;
	}

	public void setLstEstimateCosting(List<EstimateCosting> lstEstimateCosting) {
		this.lstEstimateCosting = lstEstimateCosting;
	}

	public Estimate() {
	}

	public Estimate(Long estimateId) {
		this.estimateId = estimateId;
	}

	public Estimate(Long estimateId, Long releaseId, BigDecimal totalUscost,
			BigDecimal totalLocalCost, String createdby, String lastupdatedby,
			Date lastupdateddatetime, Date createddatetime, String deletedflag) {
		this.estimateId = estimateId;
		this.releaseId = releaseId;
		this.totalUscost = totalUscost;
		this.totalLocalCost = totalLocalCost;
	
	}

	public Long getEstimateId() {
		return this.estimateId;
	}

	public void setEstimateId(Long estimateId) {
		this.estimateId = estimateId;
	}

	public Long getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(Long releaseId) {
		this.releaseId = releaseId;
	}

	public BigDecimal getTotalUscost() {
		return this.totalUscost;
	}

	public void setTotalUscost(BigDecimal totalUscost) {
		this.totalUscost = totalUscost;
	}

	public BigDecimal getTotalLocalCost() {
		return this.totalLocalCost;
	}

	public void setTotalLocalCost(BigDecimal totalLocalCost) {
		this.totalLocalCost = totalLocalCost;
	}



}
