package com.ffe.estimate.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.ffe.common.framework.model.AbstractDomain;

/**
 * Estimate generated by hbm2java
 */
public class Estimate extends AbstractDomain implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4744105404866811257L;
	private int estimateId;
	private Integer releaseId;
	private BigDecimal totalUscost;
	private BigDecimal totalLocalCost;
	private String createdby;
	private List lstEstimateCosting;


	public List getLstEstimateCosting() {
		return lstEstimateCosting;
	}

	public void setLstEstimateCosting(List lstEstimateCosting) {
		this.lstEstimateCosting = lstEstimateCosting;
	}

	public Estimate() {
	}

	public Estimate(int estimateId) {
		this.estimateId = estimateId;
	}

	public Estimate(int estimateId, Integer releaseId, BigDecimal totalUscost,
			BigDecimal totalLocalCost, String createdby, String lastupdatedby,
			Date lastupdateddatetime, Date createddatetime, String deletedflag) {
		this.estimateId = estimateId;
		this.releaseId = releaseId;
		this.totalUscost = totalUscost;
		this.totalLocalCost = totalLocalCost;
		this.createdby = createdby;
	
	}

	public int getEstimateId() {
		return this.estimateId;
	}

	public void setEstimateId(int estimateId) {
		this.estimateId = estimateId;
	}

	public Integer getReleaseId() {
		return this.releaseId;
	}

	public void setReleaseId(Integer releaseId) {
		this.releaseId = releaseId;
	}

	public BigDecimal getTotalUscost() {
		return this.totalUscost;
	}

	public void setTotalUscost(BigDecimal totalUscost) {
		this.totalUscost = totalUscost;
	}

	public BigDecimal getTotalLocalCost() {
		return this.totalLocalCost;
	}

	public void setTotalLocalCost(BigDecimal totalLocalCost) {
		this.totalLocalCost = totalLocalCost;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

}
