package com.ffe.estimate.model;
// default package
// Generated Oct 11, 2012 5:26:27 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * EstimateCosting generated by hbm2java
 */
public class EstimateCosting implements java.io.Serializable {

	private int estimateCostingId;
	private Integer estimateCostTypeId;
	private int estimateid;
	private Integer serviceId;
	private BigDecimal localCurrentCost;
	private Integer currecySelectedId;
	private Integer quantity;
	private BigDecimal totalcost;

	public EstimateCosting() {
	}

	public EstimateCosting(int estimateCostingId, int estimateid) {
		this.estimateCostingId = estimateCostingId;
		this.estimateid = estimateid;
	}

	public EstimateCosting(int estimateCostingId, Integer estimateCostTypeId,
			int estimateid, Integer serviceId, BigDecimal localCurrentCost,
			Integer currecySelectedId, Integer quantity, BigDecimal totalcost) {
		this.estimateCostingId = estimateCostingId;
		this.estimateCostTypeId = estimateCostTypeId;
		this.estimateid = estimateid;
		this.serviceId = serviceId;
		this.localCurrentCost = localCurrentCost;
		this.currecySelectedId = currecySelectedId;
		this.quantity = quantity;
		this.totalcost = totalcost;
	}

	public int getEstimateCostingId() {
		return this.estimateCostingId;
	}

	public void setEstimateCostingId(int estimateCostingId) {
		this.estimateCostingId = estimateCostingId;
	}

	public Integer getEstimateCostTypeId() {
		return this.estimateCostTypeId;
	}

	public void setEstimateCostTypeId(Integer estimateCostTypeId) {
		this.estimateCostTypeId = estimateCostTypeId;
	}

	public int getEstimateid() {
		return this.estimateid;
	}

	public void setEstimateid(int estimateid) {
		this.estimateid = estimateid;
	}

	public Integer getServiceId() {
		return this.serviceId;
	}

	public void setServiceId(Integer serviceId) {
		this.serviceId = serviceId;
	}

	public BigDecimal getLocalCurrentCost() {
		return this.localCurrentCost;
	}

	public void setLocalCurrentCost(BigDecimal localCurrentCost) {
		this.localCurrentCost = localCurrentCost;
	}

	public Integer getCurrecySelectedId() {
		return this.currecySelectedId;
	}

	public void setCurrecySelectedId(Integer currecySelectedId) {
		this.currecySelectedId = currecySelectedId;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public BigDecimal getTotalcost() {
		return this.totalcost;
	}

	public void setTotalcost(BigDecimal totalcost) {
		this.totalcost = totalcost;
	}

}
