package com.ffe.estimate.model;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

import com.ffe.common.framework.model.AbstractDomain;

/**
 * Estimate generated by hbm2java
 */
public class FilmEstimate extends AbstractDomain implements java.io.Serializable {

      private static final long serialVersionUID = -4744105404866811257L;
      private Long filmEstimateId;
      private Long estimateId;
      private Long releaseId;
      private Long localDistributor;      
      private Long releaseStudio;
      private Date releaseDate;
      private String alternateFilmTitle;
      private String version;
      private String estimateType;
      private String estimateStatus;
      private Boolean isAlternateReleaseDate;     
      private Long noOfLocation;
      private BigDecimal averageTicketPrice;
      private Long noOfPrints;
      private Long noOfScreens;
      private int recommendedBy;    
      private List<PrintCostCategory> lstPrintCostCategories;
	
      @Override
	public String toString() {
		return "FilmEstimate [filmEstimateId=" + filmEstimateId
				+ ", estimateId=" + estimateId + ", releaseId=" + releaseId
				+ ", localDistributor=" + localDistributor + ", releaseStudio="
				+ releaseStudio + ", releaseDate=" + releaseDate
				+ ", alternateFilmTitle=" + alternateFilmTitle + ", version="
				+ version + ", estimateType=" + estimateType
				+ ", estimateStatus=" + estimateStatus
				+ ", isAlternateReleaseDate=" + isAlternateReleaseDate
				+ ", noOfLocation=" + noOfLocation + ", averageTicketPrice="
				+ averageTicketPrice + ", noOfPrints=" + noOfPrints
				+ ", noOfScreens=" + noOfScreens + ", recommendedBy="
				+ recommendedBy + ", lstPrintCostCategories="
				+ lstPrintCostCategories + "]";
	}

	public Long getFilmEstimateId() {
		return filmEstimateId;
	}

	public void setFilmEstimateId(Long filmEstimateId) {
		this.filmEstimateId = filmEstimateId;
	}

	public Long getEstimateId() {
		return estimateId;
	}

	public void setEstimateId(Long estimateId) {
		this.estimateId = estimateId;
	}

	public Long getReleaseId() {
		return releaseId;
	}

	public void setReleaseId(Long releaseId) {
		this.releaseId = releaseId;
	}

	public Long getLocalDistributor() {
		return localDistributor;
	}

	public void setLocalDistributor(Long localDistributor) {
		this.localDistributor = localDistributor;
	}

	public Long getReleaseStudio() {
		return releaseStudio;
	}

	public void setReleaseStudio(Long releaseStudio) {
		this.releaseStudio = releaseStudio;
	}

	public Date getReleaseDate() {
		return releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	public String getAlternateFilmTitle() {
		return alternateFilmTitle;
	}

	public void setAlternateFilmTitle(String alternateFilmTitle) {
		this.alternateFilmTitle = alternateFilmTitle;
	}

	public String getVersion() {
		return version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	public String getEstimateType() {
		return estimateType;
	}

	public void setEstimateType(String estimateType) {
		this.estimateType = estimateType;
	}

	public String getEstimateStatus() {
		return estimateStatus;
	}

	public void setEstimateStatus(String estimateStatus) {
		this.estimateStatus = estimateStatus;
	}

	public Boolean getIsAlternateReleaseDate() {
		return isAlternateReleaseDate;
	}

	public void setIsAlternateReleaseDate(Boolean isAlternateReleaseDate) {
		this.isAlternateReleaseDate = isAlternateReleaseDate;
	}

	public Long getNoOfLocation() {
		return noOfLocation;
	}

	public void setNoOfLocation(Long noOfLocation) {
		this.noOfLocation = noOfLocation;
	}

	public BigDecimal getAverageTicketPrice() {
		return averageTicketPrice;
	}

	public void setAverageTicketPrice(BigDecimal averageTicketPrice) {
		this.averageTicketPrice = averageTicketPrice;
	}

	public Long getNoOfPrints() {
		return noOfPrints;
	}

	public void setNoOfPrints(Long noOfPrints) {
		this.noOfPrints = noOfPrints;
	}

	public Long getNoOfScreens() {
		return noOfScreens;
	}

	public void setNoOfScreens(Long noOfScreens) {
		this.noOfScreens = noOfScreens;
	}

	public int getRecommendedBy() {
		return recommendedBy;
	}

	public void setRecommendedBy(int recommendedBy) {
		this.recommendedBy = recommendedBy;
	}

	public List<PrintCostCategory> getLstPrintCostCategories() {
		return lstPrintCostCategories;
	}

	public void setLstPrintCostCategories(
			List<PrintCostCategory> lstPrintCostCategories) {
		this.lstPrintCostCategories = lstPrintCostCategories;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}
      
    
}
