package com.ffe.service.model;

import com.ffe.common.framework.model.AbstractDomain;
// default package
// Generated Oct 11, 2012 5:26:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * DigitalService generated by hbm2java
 */
public class DigitalService extends AbstractDomain implements java.io.Serializable {

	private Long digiServiceId;
	private String digiServName;
	private String digiServCode;
	private int activityId;
	private String desc;

	public DigitalService() {
	}

	public DigitalService(Long digiServiceId, String digiServName,
			String digiServCode, int activityId, String crtBy, String upBy,
			String delFlag, String desc) {
		this.digiServiceId = digiServiceId;
		this.digiServName = digiServName;
		this.digiServCode = digiServCode;
		this.activityId = activityId;
		this.desc = desc;
	}

	

	public Long getDigiServiceId() {
		return digiServiceId;
	}

	public void setDigiServiceId(Long digiServiceId) {
		this.digiServiceId = digiServiceId;
	}

	public String getDigiServName() {
		return this.digiServName;
	}

	public void setDigiServName(String digiServName) {
		this.digiServName = digiServName;
	}

	public String getDigiServCode() {
		return this.digiServCode;
	}

	public void setDigiServCode(String digiServCode) {
		this.digiServCode = digiServCode;
	}

	public int getActivityId() {
		return this.activityId;
	}

	public void setActivityId(int activityId) {
		this.activityId = activityId;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
