package com.ffe.service.model;

import com.ffe.common.framework.model.AbstractDomain;

// default package
// Generated Oct 11, 2012 5:26:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * DigitalServTempAssoc generated by hbm2java
 */
public class DigitalServTempAssoc extends AbstractDomain implements java.io.Serializable {

	private Long digiServTemplateAssocId;
	private Long digiServTemplateId;
	private Long digiServiceId;
	private String activityCode;
	private String desc;
	private DigitalService digitalService;
	

	public DigitalService getDigitalService() {
		return digitalService;
	}

	public void setDigitalService(DigitalService digitalService) {
		this.digitalService = digitalService;
	}

	public DigitalServTempAssoc() {
	}

	public DigitalServTempAssoc(Long digiServTemplateId, Long digiServiceId,
			String activityCode,
			String desc) {
		this.digiServTemplateId = digiServTemplateId;
		this.digiServiceId = digiServiceId;
		this.activityCode = activityCode;
		this.desc = desc;
	}

	public Long getDigiServTemplateAssocId() {
		return this.digiServTemplateAssocId;
	}

	public void setDigiServTemplateAssocId(Long digiServTemplateAssocId) {
		this.digiServTemplateAssocId = digiServTemplateAssocId;
	}

	public Long getDigiServTemplateId() {
		return this.digiServTemplateId;
	}

	public void setDigiServTemplateId(Long digiServTemplateId) {
		this.digiServTemplateId = digiServTemplateId;
	}

	public Long getDigiServiceId() {
		return this.digiServiceId;
	}

	public void setDigiServiceId(Long digiServiceId) {
		this.digiServiceId = digiServiceId;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
