package com.ffe.service.model;

import com.ffe.common.framework.model.AbstractDomain;

// default package
// Generated Oct 11, 2012 5:26:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * DigitalCostsVendorService generated by hbm2java
 */
public class DigitalCostsVendorService extends AbstractDomain implements java.io.Serializable {

	private Long digiVendServId;
	private String serviceName;
	private Long vendorId;
	private Long unitCost;
	private String vendServCode;
	private String digiServCode;
	private String activityCode;
	private String desc;

	public DigitalCostsVendorService() {
	}

	public DigitalCostsVendorService(Long digiVendServId, String serviceName,
			Long vendorId, Long unitCost, String vendServCode,
			String digiServCode, String activityCode, String crtBy,
			String uptBy, String delFlag, String desc) {
		this.digiVendServId = digiVendServId;
		this.serviceName = serviceName;
		this.vendorId = vendorId;
		this.unitCost = unitCost;
		this.vendServCode = vendServCode;
		this.digiServCode = digiServCode;
		this.activityCode = activityCode;
		this.desc = desc;
	}

	public Long getDigiVendServId() {
		return this.digiVendServId;
	}

	public void setDigiVendServId(Long digiVendServId) {
		this.digiVendServId = digiVendServId;
	}

	public String getServiceName() {
		return this.serviceName;
	}

	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}

	public Long getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Long vendorId) {
		this.vendorId = vendorId;
	}

	public Long getUnitCost() {
		return this.unitCost;
	}

	public void setUnitCost(Long unitCost) {
		this.unitCost = unitCost;
	}

	public String getVendServCode() {
		return this.vendServCode;
	}

	public void setVendServCode(String vendServCode) {
		this.vendServCode = vendServCode;
	}

	public String getDigiServCode() {
		return this.digiServCode;
	}

	public void setDigiServCode(String digiServCode) {
		this.digiServCode = digiServCode;
	}

	public String getActivityCode() {
		return this.activityCode;
	}

	public void setActivityCode(String activityCode) {
		this.activityCode = activityCode;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
