package com.ffe.service.model;

import com.ffe.common.framework.model.AbstractDomain;

/**
 * DigitalCostsVendor generated by hbm2java
 */
public class DigitalCostsVendor extends AbstractDomain implements java.io.Serializable {

	private Long vendorId;
	private String vendorName;
	private String desc;

	public DigitalCostsVendor() {
	}

	public DigitalCostsVendor(Long vendorId, String vendorName, String crtBy,
			String uptBy, String delFlag, String desc) {
		this.vendorId = vendorId;
		this.vendorName = vendorName;
		this.desc = desc;
	}

	

	public Long getVendorId() {
		return vendorId;
	}

	public void setVendorId(Long vendorId) {
		this.vendorId = vendorId;
	}

	public String getVendorName() {
		return this.vendorName;
	}

	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}


	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
