package com.ffe.service.model;

import java.util.List;

import com.ffe.common.framework.model.AbstractDomain;

// default package
// Generated Oct 11, 2012 5:26:27 PM by Hibernate Tools 3.4.0.CR1

/**
 * DigitalServTemplate generated by hbm2java
 */
public class DigitalServTemplate extends AbstractDomain implements java.io.Serializable {

	private Long digiServTempId;
	private String digiServTempName;
	private String desc;
	private List<DigitalServTempAssoc> digitalServTempAssoclst;

	

	public List<DigitalServTempAssoc> getDigitalServTempAssoclst() {
		return digitalServTempAssoclst;
	}

	public void setDigitalServTempAssoclst(
			List<DigitalServTempAssoc> digitalServTempAssoclst) {
		this.digitalServTempAssoclst = digitalServTempAssoclst;
	}

	public DigitalServTemplate() {
	}

	public DigitalServTemplate(String digiServTempName, String crtBy,
			String uptBy, String delFlag, String desc) {
		this.digiServTempName = digiServTempName;
		this.desc = desc;
	}

	

	public Long getDigiServTempId() {
		return digiServTempId;
	}

	public void setDigiServTempId(Long digiServTempId) {
		this.digiServTempId = digiServTempId;
	}

	public String getDigiServTempName() {
		return this.digiServTempName;
	}

	public void setDigiServTempName(String digiServTempName) {
		this.digiServTempName = digiServTempName;
	}

	public String getDesc() {
		return this.desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

}
